#############################################################################
# Makefile for building: vplot
# Generated by qmake (2.01a) (Qt 4.6.2) on: Wed Nov 11 15:31:24 2015
# Project:  VPlot.pro
# Template: app
# Command: /usr/lib64/qt4/bin/qmake -unix -o Makefile VPlot.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I/usr/include/qwt -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)   -L/usr/lib64 -lqwt -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib64/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = VPlot.cc \
		VDisplay.cc \
		Dvm.cc \
		VNS.cc \
		main.cc moc_VPlot.cpp \
		moc_VDisplay.cpp
OBJECTS       = VPlot.o \
		VDisplay.o \
		Dvm.o \
		VNS.o \
		main.o \
		moc_VPlot.o \
		moc_VDisplay.o
DIST          = /usr/lib64/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		qwt.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		VPlot.pro
QMAKE_TARGET  = vplot
DESTDIR       = 
TARGET        = vplot

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: VPlot.pro  /usr/lib64/qt4/mkspecs/linux-g++-64/qmake.conf /usr/lib64/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		qwt.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -unix -o Makefile VPlot.pro
/usr/lib64/qt4/mkspecs/common/g++-multilib.conf:
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
qwt.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile VPlot.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/vplot1.0.0 || $(MKDIR) .tmp/vplot1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/vplot1.0.0/ && $(COPY_FILE) --parents VPlot.h VDisplay.h Dvm.h VNS.h .tmp/vplot1.0.0/ && $(COPY_FILE) --parents VPlot.cc VDisplay.cc Dvm.cc VNS.cc main.cc .tmp/vplot1.0.0/ && (cd `dirname .tmp/vplot1.0.0` && $(TAR) vplot1.0.0.tar vplot1.0.0 && $(COMPRESS) vplot1.0.0.tar) && $(MOVE) `dirname .tmp/vplot1.0.0`/vplot1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/vplot1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_VPlot.cpp moc_VDisplay.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_VPlot.cpp moc_VDisplay.cpp
moc_VPlot.cpp: VNS.h \
		VPlot.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) VPlot.h -o moc_VPlot.cpp

moc_VDisplay.cpp: VDisplay.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) VDisplay.h -o moc_VDisplay.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

VPlot.o: VPlot.cc VPlot.h \
		VNS.h \
		Dvm.h \
		VDisplay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VPlot.o VPlot.cc

VDisplay.o: VDisplay.cc VDisplay.h \
		Dvm.h \
		VNS.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VDisplay.o VDisplay.cc

Dvm.o: Dvm.cc Dvm.h \
		VNS.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Dvm.o Dvm.cc

VNS.o: VNS.cc VNS.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VNS.o VNS.cc

main.o: main.cc Dvm.h \
		VPlot.h \
		VNS.h \
		VDisplay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc

moc_VPlot.o: moc_VPlot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VPlot.o moc_VPlot.cpp

moc_VDisplay.o: moc_VDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VDisplay.o moc_VDisplay.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

